# Generated by Django 2.2.dev20181212174947 on 2019-05-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_post_gistid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gistId',
            field=models.ManyToManyField(blank=True, to='operations.Gist'),
        ),
    ]
